POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe",
  "userType": "CLIENT",
  "phone": "+1234567112",
  "whatsappNo": "+1234567212",
  "email": "janedoe@mail.com",
  "state": "California",
  "password": "test"
}

###

POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "janedoe@mail.com",
  "password": "test"
}


###
GET http://localhost:4000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzkyMTJmMzk0Y2RlOTliMTI4ZGU5OTMiLCJpYXQiOjE3Mzc3ODc4NjUsImV4cCI6MTczNzgzMTA2NX0.tJM2ROWJfN_x7nhbGmW6-4IYZXiGj2kOw_hXC6rew-s

###
GET http://localhost:4000/api/user/search?search=jo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzkyMTJmMzk0Y2RlOTliMTI4ZGU5OTMiLCJpYXQiOjE3Mzc3ODc4NjUsImV4cCI6MTczNzgzMTA2NX0.tJM2ROWJfN_x7nhbGmW6-4IYZXiGj2kOw_hXC6rew-s

###
GET http://localhost:4000/api/user/679212091d9187183c84925d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzkyMTJmMzk0Y2RlOTliMTI4ZGU5OTMiLCJpYXQiOjE3Mzc3ODc4NjUsImV4cCI6MTczNzgzMTA2NX0.tJM2ROWJfN_x7nhbGmW6-4IYZXiGj2kOw_hXC6rew-s

###

GET http://localhost:4000/api/auth/refresh-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzkyMTJmMzk0Y2RlOTliMTI4ZGU5OTMiLCJpYXQiOjE3Mzc2MzAwMDgsImV4cCI6MTczODIzNDgwOH0.wpi91bl0ZJfkJzPUAvZJWergjUrZqtVEIXnjJUet1kk

###
PATCH  http://localhost:4000/api/user/679212091d9187183c84925d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzkyMTJmMzk0Y2RlOTliMTI4ZGU5OTMiLCJpYXQiOjE3Mzc2MzA4MDIsImV4cCI6MTczNzY3NDAwMn0.slpBJ4IXL4QMJpeDqxmnu3nuDgSZPsQRFP6IIrZWMls
Content-Type: application/json

{
  "firstName": "DabidUpdated"
}