POST http://localhost:4000/api/auth/register-admin
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe",
  "userType": "CLIENT",
  "phone": "+1234567112",
  "whatsappNo": "+1234567212",
  "email": "janedoe@mail.com",
  "state": "California",
  "password": "test"
}
