POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe",
  "userType": "CLIENT",
  "phone": "+1234567112",
  "whatsappNo": "+1234567212",
  "email": "janedoe@mail.com",
  "state": "California",
  "password": "test"
}

###

POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "username": "jane_doe_7984",
  "password": "test"
}


###
GET http://localhost:4000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzkyMTJmMzk0Y2RlOTliMTI4ZGU5OTMiLCJpYXQiOjE3Mzc2MzAwMDgsImV4cCI6MTczODIzNDgwOH0.wpi91bl0ZJfkJzPUAvZJWergjUrZqtVEIXnjJUet1kk

###

GET http://localhost:4000/api/auth/refresh-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzkyMTJmMzk0Y2RlOTliMTI4ZGU5OTMiLCJpYXQiOjE3Mzc2MzAwMDgsImV4cCI6MTczODIzNDgwOH0.wpi91bl0ZJfkJzPUAvZJWergjUrZqtVEIXnjJUet1kk